kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: samuelsquire/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - latest
    - '1.0.1'
    - '1.0'
